### ISSUE TITLE
npm ERR! Error: No compatible version found: debug@'^2.1.1'

### ISSUE THREAD

**Issue by darrennix** [octoblu/node-meshblu-socket.io#6]
On clean raspberry pi...

pi@raspberrypi ~ $ npm install debug@2.1.1
npm http GET http://registry.npmjs.org/debug/2.1.1
npm http 200 http://registry.npmjs.org/debug/2.1.1
npm http GET http://registry.npmjs.org/debug/-/debug-2.1.1.tgz
npm http 200 http://registry.npmjs.org/debug/-/debug-2.1.1.tgz
npm http GET http://registry.npmjs.org/ms/0.6.2
npm http 304 http://registry.npmjs.org/ms/0.6.2
debug@2.1.1 ./node_modules/debug 
└── ms@0.6.2
pi@raspberrypi ~ $ npm install meshblu
npm http GET http://registry.npmjs.org/meshblu
npm http 304 http://registry.npmjs.org/meshblu
npm http GET http://registry.npmjs.org/debug
npm http GET http://registry.npmjs.org/node-rsa
npm http GET http://registry.npmjs.org/lodash
npm http GET http://registry.npmjs.org/socket.io-client
npm http 304 http://registry.npmjs.org/debug
npm ERR! error installing meshblu@1.13.1
npm http 304 http://registry.npmjs.org/node-rsa
npm http 304 http://registry.npmjs.org/lodash
npm http 304 http://registry.npmjs.org/socket.io-client

npm ERR! Error: No compatible version found: debug@'^2.1.1'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.1.0","0.2.0","0.3.0","0.4.0","0.4.1","0.5.0","0.6.0","0.7.0","0.7.1","0.7.2","0.7.3","0.7.4","0.8.0","0.8.1","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","2.0.0","2.1.0","2.1.1"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:488:10)
npm ERR!     at /usr/share/npm/lib/cache.js:375:15
npm ERR!     at saved (/usr/share/npm/lib/utils/npm-registry-client/get.js:147:7)
npm ERR!     at Object.oncomplete (/usr/lib/nodejs/graceful-fs.js:230:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/pi/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.12.28+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "meshblu"
npm ERR! cwd /home/pi
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message No compatible version found: debug@'^2.1.1'
npm ERR! message Valid install targets:
npm ERR! message ["0.0.1","0.1.0","0.2.0","0.3.0","0.4.0","0.4.1","0.5.0","0.6.0","0.7.0","0.7.1","0.7.2","0.7.3","0.7.4","0.8.0","0.8.1","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","2.0.0","2.1.0","2.1.1"]
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm not ok

**Comment by royvandewater** [comment]
I am unable to reproduce this. It looks like NPM was able to find `2.1.1` as a valid install target, I wonder why that didn't satisfy the `^2.1.1` requirement. The current latest version of debug is `2.2.0`, so that should work as well. Let me know if this is still an issue for you with some steps to reproduce and I'll take another look at it.
